### ISSUE TITLE
posting-content gelöschter Beiträge wird nicht mehr farblich hervorgehoben

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#651]
Durch das Verwenden eines div.posting-header als flex-container ist .posting-content nicht mehr Geschwisterelement des headers. Deshalb laufen die Selektoren 

```css
.thread-message .deleted ~ .posting-content, 
.thread-message .deleted ~ .posting-content * {
    color: #900;
    border-color: #900;
}
```

ins Leere.
